Repository taeyun1215/gp-backoffice, pull requests merged in 2023-08, with the labels that each got.

#13 PR #12 코드리뷰에 대한 피드백 완료
  .gitignore
  build.gradle
  lombok.config
  src/main/java/com/example/demo/common/SuccessApiResponse.java
  src/main/java/com/example/demo/common/config/WebSecurityConfig.java
  src/main/java/com/example/demo/user/adapter/in/web/AuthController.java
  src/main/java/com/example/demo/user/adapter/in/web/UserController.java
  src/main/java/com/example/demo/user/adapter/in/web/request/CreateUserRequest.java
  src/main/java/com/example/demo/user/adapter/in/web/request/LoginRequest.java
  src/main/java/com/example/demo/user/adapter/in/web/response/LoginResponse.java
  src/main/java/com/example/demo/user/adapter/in/web/response/UserResponse.java
  src/main/java/com/example/demo/user/adapter/out/persistence/AuthenticationAdapter.java
  src/main/java/com/example/demo/user/adapter/out/persistence/PasswordEncoderAdapter.java
  src/main/java/com/example/demo/user/adapter/out/persistence/UserDetailsServiceImpl.java
  src/main/java/com/example/demo/user/adapter/out/persistence/UserLoadPersistenceAdapter.java
  src/main/java/com/example/demo/user/application/port/in/CreateUserUseCase.java
  src/main/java/com/example/demo/user/application/port/in/GetUserQuery.java
  src/main/java/com/example/demo/user/application/port/in/LoginUseCase.java
  src/main/java/com/example/demo/user/application/port/in/command/CreateUserCommand.java
  src/main/java/com/example/demo/user/application/port/in/command/LoginCommand.java
  src/main/java/com/example/demo/user/application/port/in/command/UpdateUserCommand.java
  src/main/java/com/example/demo/user/application/port/out/LoginPort.java
  src/main/java/com/example/demo/user/application/port/out/TokenGeneratorPort.java
  src/main/java/com/example/demo/user/application/port/out/response/CreateUserResponse.java
  src/main/java/com/example/demo/user/application/port/out/response/UpdateUserResponse.java
  src/main/java/com/example/demo/user/application/service/CreateUserService.java
  src/main/java/com/example/demo/user/application/service/LoadUserService.java
  src/main/java/com/example/demo/user/application/service/LoginService.java
  src/main/resources/application-local.yml
  src/test/java/com/example/demo/DemoApplicationTests.java
  src/test/java/com/example/demo/user/adapter/in/web/AuthControllerTest.java
  src/test/java/com/example/demo/user/adapter/in/web/UserControllerTest.java
  src/test/java/com/example/demo/user/adapter/out/persistence/AuthenticationAdapterTest.java
  src/test/java/com/example/demo/user/adapter/out/persistence/PasswordEncoderAdapterTest.java
  src/test/java/com/example/demo/user/adapter/out/persistence/UserDetailsServiceImplTest.java
  src/test/java/com/example/demo/user/adapter/out/persistence/UserLoadPersistenceAdapterTest.java
  src/test/java/com/example/demo/user/adapter/out/persistence/UserMapperTest.java
  src/test/java/com/example/demo/user/adapter/out/persistence/UserPersistenceAdapterTest.java
  src/test/java/com/example/demo/user/application/service/CreateUserServiceTest.java
  src/test/java/com/example/demo/user/application/service/LoadUserServiceTest.java
  src/test/java/com/example/demo/user/application/service/LoginServiceTest.java
Labels: 🔨 Refactor

#16 PR #15에 대한 코드리뷰 피드백 반영 완료
  src/main/java/com/example/demo/attendance/adapter/in/request/SearchAttendanceRequest.java
  src/main/java/com/example/demo/attendance/adapter/in/response/AttendanceResponseMapper.java
  src/main/java/com/example/demo/attendance/adapter/in/response/SearchAttendanceResponse.java
  src/main/java/com/example/demo/attendance/adapter/in/web/SearchAttendanceController.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/AttendanceJpaRepo.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/AttendanceJpaRepoCustom.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/AttendanceJpaRepoImpl.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/AttendancePersistenceAdapter.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/AttendancePersistenceMapper.java
  src/main/java/com/example/demo/attendance/application/port/in/command/RegisterAttendanceCommand.java
  src/main/java/com/example/demo/attendance/application/port/in/query/SearchAttendanceCriteria.java
  src/main/java/com/example/demo/attendance/application/port/in/query/SearchAttendanceQuery.java
  src/main/java/com/example/demo/attendance/application/port/in/usecase/SearchAttendanceUseCase.java
  src/main/java/com/example/demo/attendance/application/port/out/SearchAttendancePort.java
  src/main/java/com/example/demo/attendance/application/service/SearchAttendanceService.java
  src/main/java/com/example/demo/attendance/domain/AttendanceSearchPeriod.java
  src/test/java/com/example/demo/attendance/adapter/in/RegisterAttendanceControllerTest.java
  src/test/java/com/example/demo/attendance/adapter/in/SearchAttendanceControllerTest.java
  src/test/java/com/example/demo/attendance/adapter/out/AttendanceJpaRepoImplIT.java
  src/test/java/com/example/demo/attendance/adapter/out/AttendanceJpaRepoImplTest.java
  src/test/java/com/example/demo/attendance/adapter/out/AttendancePersistenceAdapterTest.java
  src/test/java/com/example/demo/attendance/application/RegisterAttendanceServiceTest.java
  src/test/java/com/example/demo/attendance/application/SearchAttendanceServiceTest.java
  src/test/java/com/example/demo/attendance/domain/AttendanceSearchPeriodTest.java
  src/test/java/com/example/demo/attendance/domain/AttendanceTest.java
Labels: 🔨 Refactor

#19 PR #15에 대한 코드리뷰 피드백 반영 완료
  build.gradle
  src/main/java/com/example/demo/attendance/adapter/in/request/SearchAttendanceRequest.java
  src/main/java/com/example/demo/attendance/adapter/in/web/SearchAttendanceController.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/AttendanceJpaRepoCustom.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/AttendanceJpaRepoImpl.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/AttendancePersistenceAdapter.java
  src/main/java/com/example/demo/attendance/application/port/in/query/SearchAttendanceCriteria.java
  src/main/java/com/example/demo/attendance/application/port/in/query/SearchAttendanceQuery.java
  src/main/java/com/example/demo/attendance/application/port/in/query/SearchAttendanceQueryParameters.java
  src/main/java/com/example/demo/attendance/application/port/out/SearchAttendancePort.java
  src/main/java/com/example/demo/attendance/application/service/SearchAttendanceService.java
  src/main/java/com/example/demo/attendance/domain/AttendanceSearchCriteria.java
  src/main/java/com/example/demo/user/adapter/in/web/request/LoginRequest.java
  src/test/java/com/example/demo/attendance/adapter/in/RegisterAttendanceControllerTest.java
  src/test/java/com/example/demo/attendance/adapter/in/SearchAttendanceControllerTest.java
  src/test/java/com/example/demo/attendance/adapter/out/AttendanceJpaRepoImplIT.java
  src/test/java/com/example/demo/attendance/adapter/out/AttendanceJpaRepoImplTest.java
  src/test/java/com/example/demo/attendance/adapter/out/AttendancePersistenceAdapterTest.java
  src/test/java/com/example/demo/attendance/application/RegisterAttendanceServiceTest.java
  src/test/java/com/example/demo/attendance/application/SearchAttendanceServiceTest.java
  src/test/java/com/example/demo/attendance/domain/AttendanceSearchCriteriaTest.java
  src/test/java/com/example/demo/attendance/domain/AttendanceSearchPeriodTest.java
  src/test/java/com/example/demo/attendance/domain/AttendanceTest.java
Labels: 🔨 Refactor

#23 PR #21, #22 코드리뷰 피드백 반영 완료
  src/main/java/com/example/demo/attendance/adapter/in/request/RegisterAttendanceRequest.java
  src/main/java/com/example/demo/attendance/adapter/in/request/RegisterFixedStartTimeRequest.java
  src/main/java/com/example/demo/attendance/adapter/in/request/SearchAttendanceRequest.java
  src/main/java/com/example/demo/attendance/adapter/in/response/AttendanceResponseMapper.java
  src/main/java/com/example/demo/attendance/adapter/in/response/SearchAttendanceResponse.java
  src/main/java/com/example/demo/attendance/adapter/in/web/RegisterAttendanceController.java
  src/main/java/com/example/demo/attendance/adapter/in/web/RegisterFixedStartTimeController.java
  src/main/java/com/example/demo/attendance/adapter/in/web/SearchAttendanceController.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/Attendance/AttendanceJpaEntity.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/Attendance/AttendanceJpaRepo.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/Attendance/AttendanceJpaRepoCustom.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/Attendance/AttendanceJpaRepoImpl.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/Attendance/AttendancePersistenceAdapter.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/Attendance/AttendancePersistenceMapper.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/AttendanceJpaRepoCustom.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/FixedStartTime/FixedStartTimeJpaEntity.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/FixedStartTime/FixedStartTimeJpaRepo.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/FixedStartTime/FixedStartTimePersistenceAdapter.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/FixedStartTime/FixedStartTimePersistenceMapper.java
  src/main/java/com/example/demo/attendance/application/port/in/command/RegisterAttendanceCommand.java
  src/main/java/com/example/demo/attendance/application/port/in/command/RegisterFixedStartTimeCommand.java
  src/main/java/com/example/demo/attendance/application/port/in/usecase/RegisterFixedStartTimeUseCase.java
  src/main/java/com/example/demo/attendance/application/port/out/LoadFixedStartTimePort.java
  src/main/java/com/example/demo/attendance/application/port/out/SaveFixedStartTimePort.java
  src/main/java/com/example/demo/attendance/application/port/out/UpdateAttendanceStatusPort.java
  src/main/java/com/example/demo/attendance/application/service/RegisterAttendanceService.java
  src/main/java/com/example/demo/attendance/application/service/RegisterFixedStartTimeService.java
  src/main/java/com/example/demo/attendance/domain/Attendance.java
  src/main/java/com/example/demo/attendance/domain/FixedStartTime.java
  src/main/java/com/example/demo/user/adapter/in/web/request/LoginRequest.java
  src/test/java/com/example/demo/attendance/adapter/in/RegisterFixedStartTimeControllerTest.java
  src/test/java/com/example/demo/attendance/adapter/out/AttendanceJpaRepoImplIT.java
  src/test/java/com/example/demo/attendance/adapter/out/AttendanceJpaRepoImplTest.java
  src/test/java/com/example/demo/attendance/adapter/out/AttendancePersistenceAdapterTest.java
  src/test/java/com/example/demo/attendance/domain/AttendanceTest.java
Labels: 🐞 BugFix, ✅ TestCode, 🔨 Refactor, ✨ Feature

#24 refactor : add Attendance column FixedStartTime
  src/main/java/com/example/demo/attendance/adapter/out/persistence/Attendance/AttendanceJpaEntity.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/Attendance/AttendanceJpaRepoImpl.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/Attendance/AttendancePersistenceMapper.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/FixedStartTime/FixedStartTimePersistenceMapper.java
  src/main/java/com/example/demo/attendance/application/service/RegisterAttendanceService.java
  src/main/java/com/example/demo/attendance/application/service/RegisterFixedStartTimeService.java
  src/main/java/com/example/demo/attendance/domain/Attendance.java
  src/main/java/com/example/demo/attendance/domain/FixedStartTime.java
Labels: 🔨 Refactor

#26 feat : add Attendance column lateReason and API SubmissionLateReason
  src/main/java/com/example/demo/attendance/adapter/in/request/SearchAttendanceRequest.java
  src/main/java/com/example/demo/attendance/adapter/in/request/SubmissionLateReasonRequest.java
  src/main/java/com/example/demo/attendance/adapter/in/response/AttendanceResponseMapper.java
  src/main/java/com/example/demo/attendance/adapter/in/response/SearchAttendanceResponse.java
  src/main/java/com/example/demo/attendance/adapter/in/web/SubmissionLateReasonController.java
  src/main/java/com/example/demo/attendance/adapter/in/web/UpdateFixedStartTimeController.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/Attendance/AttendanceJpaEntity.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/Attendance/AttendancePersistenceAdapter.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/Attendance/AttendancePersistenceMapper.java
  src/main/java/com/example/demo/attendance/application/port/in/command/SubmissionLateReasonCommand.java
  src/main/java/com/example/demo/attendance/application/port/in/usecase/SubmissionLateReasonUseCase.java
  src/main/java/com/example/demo/attendance/application/port/out/LoadAttendancePort.java
  src/main/java/com/example/demo/attendance/application/port/out/SaveLateReasonPort.java
  src/main/java/com/example/demo/attendance/application/service/SubmissionLateReasonService.java
  src/main/java/com/example/demo/attendance/domain/Attendance.java
Labels: 🔨 Refactor, ✨ Feature

#27 refactor : update attendance domain entity column
  src/main/java/com/example/demo/attendance/adapter/in/response/AttendanceResponseMapper.java
  src/main/java/com/example/demo/attendance/adapter/in/response/SearchAttendanceResponse.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/Attendance/AttendanceJpaRepo.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/Attendance/AttendanceJpaRepoCustom.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/Attendance/AttendanceJpaRepoImpl.java
  src/main/java/com/example/demo/attendance/adapter/out/persistence/Attendance/AttendancePersistenceAdapter.java
  src/main/java/com/example/demo/attendance/application/port/out/LoadAttendancePort.java
  src/main/java/com/example/demo/attendance/application/service/RegisterAttendanceService.java
  src/main/java/com/example/demo/attendance/application/service/SubmissionLateReasonService.java
  src/main/java/com/example/demo/attendance/domain/Attendance.java
Labels: 🐞 BugFix, 🔨 Refactor
